language: node_js
node_js:
  - stable
cache:
  directories:
    - "node_modules"

# safelist
branches:
  only:
    - master
deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
  region: "us-west-1"
  app: "supreme"
  env: "supreme-api"
  bucket_name: "travis-files-api"